import type { ILoadingOverlayComp, ILoadingOverlayParams } from "ag-grid-community";
import { colorSchemeDarkBlue, themeQuartz } from "ag-grid-community";
import { colorSchemeLightWarm } from "ag-grid-community";
import loaderSVG from "@images/agLoader.svg";

export type ActionButtonDisplayMode = 'icon-only' | 'icon-text';

export const greenTema = themeQuartz
    .withPart(colorSchemeDarkBlue)
    .withParams({
        accentColor: '#86C900',
        borderRadius: 2,
        cellHorizontalPaddingScale: 0.7,
        headerFontSize: 14,
        headerFontWeight: 400,
        headerTextColor: '#CFDFC6',
        rowVerticalPaddingScale: 0.9,
        sidePanelBorder: true,
    });

export const greenTemaLight = themeQuartz
    .withPart(colorSchemeLightWarm)
    .withParams({
        accentColor: '#86C900',
        borderRadius: 2,
        cellHorizontalPaddingScale: 0.7,
        headerFontSize: 14,
        headerFontWeight: 400,
        headerTextColor: '#4F5A49',
        rowVerticalPaddingScale: 0.9,
        sidePanelBorder: true,
    });


export class CustomLoadingOverlay implements ILoadingOverlayComp {
    private eGui!: HTMLDivElement;

    private getMessage(params: ILoadingOverlayParams): string {
        const customParams = params as ILoadingOverlayParams & { loadingMessage?: string };

        return customParams.loadingMessage || "Memuat...";
    }

    public init(params: ILoadingOverlayParams): void {
        this.eGui = document.createElement("div");
        this.render(this.getMessage(params));
    }

    public getGui(): HTMLElement {
        return this.eGui;
    }

    public refresh(params: ILoadingOverlayParams): void {
        this.render(this.getMessage(params));
    }

    private render(message: string): void {
        this.eGui.innerHTML = "";

        const wrapper = document.createElement("div");
        wrapper.className = "ag-overlay-loading-center !border-0 !rounded-md";
        wrapper.setAttribute("role", "presentation");

        const loader = document.createElement("div");
        loader.className = "ag-custom-loader";
        loader.setAttribute("role", "presentation");
        loader.style.height = "75px";
        loader.style.width = "75px";
        loader.style.margin = "0 auto";
        loader.style.background = `url(${loaderSVG}) center / contain no-repeat`;

        const text = document.createElement("div");
        text.setAttribute("aria-live", "polite");
        text.setAttribute("aria-atomic", "true");
        text.textContent = message;

        wrapper.append(loader, text);
        this.eGui.append(wrapper);
    }
}


export const AG_GRID_LOCALE_ID = {
    // Set Filter
    selectAll: "(Pilih semua)",
    selectAllSearchResults: "(Pilih semua hasil pencarian)",
    addCurrentSelectionToFilter: "Tambahkan pilihan saat ini ke filter",
    searchOoo: "Cari...",
    blanks: "(Kosong)",
    noMatches: "Tidak ada yang cocok",

    filterOoo: "Saring...",
    equals: "Sama dengan",
    notEqual: "Tidak sama dengan",
    blank: "Kosong",
    notBlank: "Tidak kosong",
    empty: "Pilih salah satu",

    lessThan: "Kurang dari",
    greaterThan: "Lebih dari",
    lessThanOrEqual: "Kurang dari atau sama dengan",
    greaterThanOrEqual: "Lebih dari atau sama dengan",
    inRange: "Di antara",
    inRangeStart: "Dari",
    inRangeEnd: "Sampai",

    contains: "Mengandung",
    notContains: "Tidak mengandung",
    startsWith: "Dimulai dengan",
    endsWith: "Diakhiri dengan",

    dateFormatOoo: "yyyy-mm-dd",
    before: "Sebelum",
    after: "Sesudah",

    andCondition: "DAN",
    orCondition: "ATAU",

    applyFilter: "Terapkan",
    resetFilter: "Atur Ulang",
    clearFilter: "Bersihkan",
    cancelFilter: "Batal",

    textFilter: "Filter Teks",
    numberFilter: "Filter Angka",
    dateFilter: "Filter Tanggal",
    setFilter: "Filter Set",

    groupFilterSelect: "Pilih kolom:",

    // Advanced Filter
    advancedFilterContains: "mengandung",
    advancedFilterNotContains: "tidak mengandung",
    advancedFilterTextEquals: "sama dengan",
    advancedFilterTextNotEqual: "tidak sama dengan",
    advancedFilterStartsWith: "dimulai dengan",
    advancedFilterEndsWith: "diakhiri dengan",
    advancedFilterBlank: "kosong",
    advancedFilterNotBlank: "tidak kosong",
    advancedFilterEquals: "=",
    advancedFilterNotEqual: "!=",
    advancedFilterGreaterThan: ">",
    advancedFilterGreaterThanOrEqual: ">=",
    advancedFilterLessThan: "<",
    advancedFilterLessThanOrEqual: "<=",
    advancedFilterTrue: "benar",
    advancedFilterFalse: "salah",
    advancedFilterAnd: "DAN",
    advancedFilterOr: "ATAU",
    advancedFilterApply: "Terapkan",
    advancedFilterBuilder: "Builder",
    advancedFilterValidationMissingColumn: "Kolom hilang",
    advancedFilterValidationMissingOption: "Opsi hilang",
    advancedFilterValidationMissingValue: "Nilai hilang",
    advancedFilterValidationInvalidColumn: "Kolom tidak ditemukan",
    advancedFilterValidationInvalidOption: "Opsi tidak ditemukan",
    advancedFilterValidationMissingQuote: "Tanda kutip akhir hilang",
    advancedFilterValidationNotANumber: "Nilai bukan angka",
    advancedFilterValidationInvalidDate: "Nilai bukan tanggal yang valid",
    advancedFilterValidationMissingCondition: "Kondisi hilang",
    advancedFilterValidationJoinOperatorMismatch:
        "Operator dalam kondisi harus sama",
    advancedFilterValidationInvalidJoinOperator: "Operator tidak valid",
    advancedFilterValidationMissingEndBracket: "Kurung tutup hilang",
    advancedFilterValidationExtraEndBracket: "Terlalu banyak kurung tutup",
    advancedFilterValidationMessage:
        "Ekspresi salah. ${variable} - ${variable}.",
    advancedFilterValidationMessageAtEnd:
        "Ekspresi salah di akhir. ${variable}.",
    advancedFilterBuilderTitle: "Filter Lanjutan",
    advancedFilterBuilderApply: "Terapkan",
    advancedFilterBuilderCancel: "Batal",
    advancedFilterBuilderAddButtonTooltip: "Tambah filter atau grup",
    advancedFilterBuilderRemoveButtonTooltip: "Hapus",
    advancedFilterBuilderMoveUpButtonTooltip: "Pindah ke atas",
    advancedFilterBuilderMoveDownButtonTooltip: "Pindah ke bawah",
    advancedFilterBuilderAddJoin: "Tambah grup",
    advancedFilterBuilderAddCondition: "Tambah filter",
    advancedFilterBuilderSelectColumn: "Pilih kolom",
    advancedFilterBuilderSelectOption: "Pilih opsi",
    advancedFilterBuilderEnterValue: "Masukkan nilai...",
    advancedFilterBuilderValidationAlreadyApplied: "Filter sudah diterapkan.",
    advancedFilterBuilderValidationIncomplete: "Kondisi belum lengkap.",
    advancedFilterBuilderValidationSelectColumn: "Pilih kolom.",
    advancedFilterBuilderValidationSelectOption: "Pilih opsi.",
    advancedFilterBuilderValidationEnterValue: "Masukkan nilai.",

    columns: "Kolom",
    filters: "Filter",

    pivotMode: "Mode Pivot",
    groups: "Kelompok Baris",
    rowGroupColumnsEmptyMessage: "Tarik ke sini untuk mengelompokkan baris",
    values: "Nilai",
    valueColumnsEmptyMessage: "Tarik ke sini untuk agregasi",
    pivots: "Kolom Pivot",
    pivotColumnsEmptyMessage: "Tarik ke sini untuk pivot kolom",

    group: "Grup",
    rowDragRow: "baris",
    rowDragRows: "baris",

    loadingOoo: "Memuat...",
    loadingError: "Terdapat Kesalahan",
    noRowsToShow: "Tidak ada data",
    enabled: "Diaktifkan",

    pinColumn: "Sematkan kolom",
    pinLeft: "Semat kiri",
    pinRight: "Semat kanan",
    noPin: "Lepaskan",
    valueAggregation: "Agregasi Nilai",
    noAggregation: "Tidak Ada",
    autosizeThisColumn: "Atur otomatis kolom ini",
    autosizeAllColumns: "Atur otomatis semua kolom",
    groupBy: "Kelompokkan berdasarkan",
    ungroupBy: "Lepas kelompok",
    ungroupAll: "Lepas semua kelompok",
    addToValues: "Tambahkan ${variable} ke nilai",
    removeFromValues: "Hapus ${variable} dari nilai",
    addToLabels: "Tambahkan ${variable} ke label",
    removeFromLabels: "Hapus ${variable} dari label",
    resetColumns: "Reset Kolom",
    expandAll: "Buka semua grup",
    collapseAll: "Tutup semua grup",
    copy: "Salin",
    ctrlC: "Ctrl+C",
    ctrlX: "Ctrl+X",
    copyWithHeaders: "Salin dengan header",
    copyWithGroupHeaders: "Salin dengan header grup",
    cut: "Potong",
    paste: "Tempel",
    ctrlV: "Ctrl+V",
    export: "Ekspor",
    csvExport: "Ekspor ke CSV",
    excelExport: "Ekspor ke Excel",
    columnFilter: "Filter Kolom",
    columnChooser: "Pilih Kolom",
    chooseColumns: "Pilih Kolom",
    sortAscending: "Urutkan Naik",
    sortDescending: "Urutkan Turun",
    sortUnSort: "Hapus Urutan",

    sum: "Jumlah",
    first: "Pertama",
    last: "Terakhir",
    min: "Minimum",
    max: "Maksimum",
    none: "Tidak ada",
    count: "Jumlah",
    avg: "Rata-rata",
    filteredRows: "Difilter",
    selectedRows: "Dipilih",
    totalRows: "Total Baris",
    totalAndFilteredRows: "Baris",
    more: "Lebih",
    to: "ke",
    of: "dari",
    page: "Halaman",
    pageLastRowUnknown: "?",
    nextPage: "Halaman Selanjutnya",
    lastPage: "Halaman Terakhir",
    firstPage: "Halaman Pertama",
    previousPage: "Halaman Sebelumnya",
    pageSizeSelectorLabel: "Ukuran halaman:",
    footerTotal: "Total",
    statusBarLastRowUnknown: "?",
    scrollColumnIntoView: "Gulir ke kolom ${variable}",

    pivotColumnGroupTotals: "Total",

    // Chart Menu
    pivotChartAndPivotMode: "Grafik Pivot & Mode Pivot",
    pivotChart: "Grafik Pivot",
    chartRange: "Rentang Grafik",
    columnChart: "Kolom",
    groupedColumn: "Dikelompokkan",
    stackedColumn: "Bertumpuk",
    normalizedColumn: "100% Bertumpuk",
    barChart: "Batang",
    groupedBar: "Dikelompokkan",
    stackedBar: "Bertumpuk",
    normalizedBar: "100% Bertumpuk",
    pieChart: "Pai",
    pie: "Pai",
    donut: "Donat",
    lineChart: "Garis",
    stackedLine: "Garis Bertumpuk",
    normalizedLine: "100% Bertumpuk",
    xyChart: "X Y (Sebar)",
    scatter: "Sebar",
    bubble: "Gelembung",
    areaChart: "Area",
    area: "Area",
    stackedArea: "Area Bertumpuk",
    normalizedArea: "100% Bertumpuk",
    histogramChart: "Histogram",
    polarChart: "Polar",
    radarLine: "Radar Garis",
    radarArea: "Radar Area",
    nightingale: "Nightingale",
    radialColumn: "Kolom Radial",
    radialBar: "Batang Radial",
    statisticalChart: "Statistik",
    boxPlot: "Box Plot",
    rangeBar: "Rentang Batang",
    rangeArea: "Rentang Area",
    hierarchicalChart: "Hierarkis",
    treemap: "Treemap",
    sunburst: "Sunburst",
    specializedChart: "Spesialisasi",
    waterfall: "Waterfall",
    heatmap: "Heatmap",
    combinationChart: "Gabungan",
    columnLineCombo: "Kolom & Garis",
    AreaColumnCombo: "Area & Kolom",

    pivotChartTitle: "Grafik Pivot",
    rangeChartTitle: "Grafik Rentang",
    settings: "Grafik",
    data: "Data",
    format: "Format",
    categories: "Kategori",
    defaultCategory: "(Tidak Ada)",
    series: "Seri",
    switchCategorySeries: "Tukar Kategori / Seri",
    categoryValues: "Nilai Kategori",
    seriesLabels: "Label Seri",
    aggregate: "Agregat",
    xyValues: "Nilai X Y",
    paired: "Mode Berpasangan",
    axis: "Sumbu",
    xAxis: "Sumbu Horizontal",
    yAxis: "Sumbu Vertikal",
    polarAxis: "Sumbu Polar",
    radiusAxis: "Sumbu Radius",
    navigator: "Navigator",
    zoom: "Perbesar",
    animation: "Animasi",
    crosshair: "Garis Bidik",
    color: "Warna",
    thickness: "Ketebalan",
    preferredLength: "Panjang yang Diinginkan",
    xType: "Tipe X",
    axisType: "Tipe Sumbu",
    automatic: "Otomatis",
    category: "Kategori",
    number: "Angka",
    time: "Waktu",
    timeFormat: "Format Waktu",
    autoRotate: "Putar Otomatis",
    labelRotation: "Rotasi Label",
    circle: "Lingkaran",
    polygon: "Poligon",
    square: "Persegi",
    cross: "Silang",
    diamond: "Berlian",
    plus: "Plus",
    triangle: "Segitiga",
    heart: "Hati",
    orientation: "Orientasi",
    fixed: "Tetap",
    parallel: "Sejajar",
    perpendicular: "Tegak Lurus",
    radiusAxisPosition: "Posisi",
    ticks: "Tanda",
    gridLines: "Garis Kisi",
    width: "Lebar",
    height: "Tinggi",
    length: "Panjang",
    padding: "Padding",
    spacing: "Spasi",
    chartStyle: "Gaya Grafik",
    title: "Judul",
    chartTitles: "Judul Grafik",
    chartTitle: "Judul Grafik",
    chartSubtitle: "Subjudul",
    horizontalAxisTitle: "Judul Sumbu Horizontal",
    verticalAxisTitle: "Judul Sumbu Vertikal",
    polarAxisTitle: "Judul Sumbu Polar",
    titlePlaceholder: "Judul Grafik",
    background: "Latar Belakang",
    font: "Font",
    weight: "Berat",
    top: "Atas",
    right: "Kanan",
    bottom: "Bawah",
    left: "Kiri",
    labels: "Label",
    calloutLabels: "Label Panggilan",
    sectorLabels: "Label Sektor",
    positionRatio: "Rasio Posisi",
    size: "Ukuran",
    shape: "Bentuk",
    minSize: "Ukuran Minimum",
    maxSize: "Ukuran Maksimum",
    legend: "Legenda",
    position: "Posisi",
    markerSize: "Ukuran Penanda",
    markerStroke: "Garis Penanda",
    markerPadding: "Padding Penanda",
    itemSpacing: "Spasi Item",
    itemPaddingX: "Padding Item X",
    itemPaddingY: "Padding Item Y",
    layoutHorizontalSpacing: "Spasi Horizontal",
    layoutVerticalSpacing: "Spasi Vertikal",
    strokeWidth: "Ketebalan Garis",
    offset: "Offset",
    offsets: "Offset",
    tooltips: "Tooltip",
    callout: "Panggilan",
    markers: "Penanda",
    shadow: "Bayangan",
    blur: "Kabur",
    xOffset: "Offset X",
    yOffset: "Offset Y",
    lineWidth: "Lebar Garis",
    lineDash: "Garis Putus-putus",
    lineDashOffset: "Offset Garis Putus-putus",
    scrollingZoom: "Zoom Gulir",
    scrollingStep: "Langkah Gulir",
    selectingZoom: "Pemilihan",
    durationMillis: "Durasi (ms)",
    crosshairLabel: "Label",
    crosshairSnap: "Snap ke Titik",
    normal: "Normal",
    bold: "Tebal",
    italic: "Miring",
    boldItalic: "Tebal Miring",
    predefined: "Prasetel",
    fillOpacity: "Opasitas Isi",
    strokeColor: "Warna Garis",
    strokeOpacity: "Opasitas Garis",
    miniChart: "Mini Grafik",
    histogramBinCount: "Jumlah Bin",
    connectorLine: "Garis Penghubung",
    seriesItems: "Item Seri",
    seriesItemType: "Tipe Item",
    seriesItemPositive: "Positif",
    seriesItemNegative: "Negatif",
    seriesItemLabels: "Label Item",
    columnGroup: "Kolom",
    barGroup: "Batang",
    pieGroup: "Pai",
    lineGroup: "Garis",
    scatterGroup: "X Y (Sebaran)",
    areaGroup: "Area",
    polarGroup: "Polar",
    statisticalGroup: "Statistik",
    hierarchicalGroup: "Hierarki",
    specializedGroup: "Spesialisasi",
    combinationGroup: "Kombinasi",
    groupedColumnTooltip: "Dikelompokkan",
    stackedColumnTooltip: "Ditumpuk",
    normalizedColumnTooltip: "100% Ditumpuk",
    groupedBarTooltip: "Dikelompokkan",
    stackedBarTooltip: "Ditumpuk",
    normalizedBarTooltip: "100% Ditumpuk",
    pieTooltip: "Pai",
    donutTooltip: "Donat",
    lineTooltip: "Garis",
    stackedLineTooltip: "Tumpuk",
    normalizedLineTooltip: "100% Tumpuk",
    groupedAreaTooltip: "Area",
    stackedAreaTooltip: "Ditumpuk",
    normalizedAreaTooltip: "100% Ditumpuk",
    scatterTooltip: "Sebaran",
    bubbleTooltip: "Gelembung",
    histogramTooltip: "Histogram",
    radialColumnTooltip: "Kolom Radial",
    radialBarTooltip: "Batang Radial",
    radarLineTooltip: "Garis Radar",
    radarAreaTooltip: "Area Radar",
    nightingaleTooltip: "Nightingale",
    rangeBarTooltip: "Rentang Batang",
    rangeAreaTooltip: "Rentang Area",
    boxPlotTooltip: "Box Plot",
    treemapTooltip: "Treemap",
    sunburstTooltip: "Sunburst",
    waterfallTooltip: "Waterfall",
    heatmapTooltip: "Peta Panas",
    columnLineComboTooltip: "Kolom dan Garis",
    areaColumnComboTooltip: "Area dan Kolom",
    customComboTooltip: "Kombinasi Kustom",
    innerRadius: "Radius Dalam",
    startAngle: "Sudut Awal",
    endAngle: "Sudut Akhir",
    reverseDirection: "Arah Terbalik",
    groupPadding: "Padding Grup",
    seriesPadding: "Padding Seri",
    tile: "Ubin",
    whisker: "Kumis",
    cap: "Tutup",
    capLengthRatio: "Rasio Panjang Tutup",
    labelPlacement: "Penempatan Label",
    inside: "Di Dalam",
    outside: "Di Luar",
    noDataToChart: "Tidak ada data untuk ditampilkan.",
    pivotChartRequiresPivotMode:
        "Grafik Pivot memerlukan mode pivot diaktifkan.",
    chartSettingsToolbarTooltip: "Menu",
    chartLinkToolbarTooltip: "Terkait dengan Grid",
    chartUnlinkToolbarTooltip: "Tidak Terkait dari Grid",
    chartDownloadToolbarTooltip: "Unduh Grafik",
    chartMenuToolbarTooltip: "Menu",
    chartEdit: "Edit Grafik",
    chartAdvancedSettings: "Pengaturan Lanjutan",
    chartLink: "Tautkan ke Grid",
    chartUnlink: "Putuskan dari Grid",
    chartDownload: "Unduh Grafik",
    histogramFrequency: "Frekuensi",
    seriesChartType: "Tipe Grafik Seri",
    seriesType: "Tipe Seri",
    secondaryAxis: "Sumbu Sekunder",
    seriesAdd: "Tambah Seri",
    categoryAdd: "Tambah Kategori",
    bar: "Batang",
    column: "Kolom",
    histogram: "Histogram",
    advancedSettings: "Pengaturan Lanjutan",
    direction: "Arah",
    horizontal: "Horizontal",
    vertical: "Vertikal",
    seriesGroupType: "Tipe Grup Seri",
    groupedSeriesGroupType: "Dikelompokkan",
    stackedSeriesGroupType: "Ditumpuk",
    normalizedSeriesGroupType: "100% Ditumpuk",
    legendEnabled: "Diaktifkan",
    invalidColor: "Nilai warna tidak valid",
    groupedColumnFull: "Kolom Dikelompokkan",
    stackedColumnFull: "Kolom Ditumpuk",
    normalizedColumnFull: "Kolom 100% Ditumpuk",
    groupedBarFull: "Batang Dikelompokkan",
    stackedBarFull: "Batang Ditumpuk",
    normalizedBarFull: "Batang 100% Ditumpuk",
    stackedAreaFull: "Area Ditumpuk",
    normalizedAreaFull: "Area 100% Ditumpuk",
    customCombo: "Kombinasi Kustom",
    funnel: "Corong",
    coneFunnel: "Corong Kerucut",
    pyramid: "Piramida",
    funnelGroup: "Corong",
    funnelTooltip: "Corong",
    coneFunnelTooltip: "Corong Kerucut",
    pyramidTooltip: "Piramida",
    dropOff: "Penurunan",
    stageLabels: "Label Tahapan",
    reverse: "Balik",

    ariaAdvancedFilterBuilderItem:
        "${variable}. Tingkat ${variable}. Tekan ENTER untuk mengedit.",
    ariaAdvancedFilterBuilderItemValidation:
        "${variable}. Tingkat ${variable}. ${variable} Tekan ENTER untuk mengedit.",
    ariaAdvancedFilterBuilderList: "Daftar Pembuat Filter Lanjutan",
    ariaAdvancedFilterBuilderFilterItem: "Kondisi Filter",
    ariaAdvancedFilterBuilderGroupItem: "Grup Filter",
    ariaAdvancedFilterBuilderColumn: "Kolom",
    ariaAdvancedFilterBuilderOption: "Opsi",
    ariaAdvancedFilterBuilderValueP: "Nilai",
    ariaAdvancedFilterBuilderJoinOperator: "Operator Penggabung",
    ariaAdvancedFilterInput: "Input Filter Lanjutan",
    ariaChecked: "dicentang",
    ariaColumn: "Kolom",
    ariaColumnGroup: "Grup Kolom",
    ariaColumnFiltered: "Kolom difilter",
    ariaColumnSelectAll: "Aktifkan/nonaktifkan semua kolom",
    ariaDateFilterInput: "Input Filter Tanggal",
    ariaDefaultListName: "Daftar",
    ariaFilterColumnsInput: "Input untuk memfilter kolom",
    ariaFilterFromValue: "Filter dari nilai",
    ariaFilterInput: "Input Filter",
    ariaFilterList: "Daftar Filter",
    ariaFilterToValue: "Filter hingga nilai",
    ariaFilterValue: "Nilai Filter",
    ariaFilterMenuOpen: "Buka menu filter",
    ariaFilteringOperator: "Operator Filter",
    ariaHidden: "tersembunyi",
    ariaIndeterminate: "tidak pasti",
    ariaInputEditor: "Editor Input",
    ariaMenuColumn: "Tekan ALT BAWAH untuk membuka menu kolom",
    ariaFilterColumn: "Tekan CTRL ENTER untuk membuka filter",
    ariaRowDeselect: "Tekan SPASI untuk batal pilih baris ini",
    ariaHeaderSelection: "Kolom dengan pilihan header",
    ariaSelectAllCells: "Tekan SPASI untuk pilih semua sel",
    ariaRowSelectAll: "Tekan SPASI untuk aktifkan/nonaktifkan semua baris",
    ariaRowToggleSelection:
        "Tekan SPASI untuk aktifkan/nonaktifkan pilihan baris",
    ariaRowSelect: "Tekan SPASI untuk pilih baris ini",
    ariaRowSelectionDisabled: "Pemilihan baris dinonaktifkan untuk baris ini",
    ariaSearch: "Pencarian",
    ariaSortableColumn: "Tekan ENTER untuk mengurutkan",
    ariaToggleVisibility: "Tekan SPASI untuk aktifkan/nonaktifkan visibilitas",
    ariaToggleCellValue: "Tekan SPASI untuk aktifkan/nonaktifkan nilai sel",
    ariaUnchecked: "tidak dicentang",
    ariaVisible: "terlihat",
    ariaSearchFilterValues: "Cari nilai filter",
    ariaPageSizeSelectorLabel: "Ukuran halaman",
    ariaChartMenuClose: "Tutup menu pengeditan grafik",
    ariaChartSelected: "Dipilih",
    ariaSkeletonCellLoadingFailed: "Baris gagal dimuat",
    ariaSkeletonCellLoading: "Memuat data baris",
};
